{"title": "Python traceback 获取详细的异常信息 - 个人文章 ", "index": "python", "content": "python中用于处理异常栈的模块是traceback模块，它提供了print_exception、format_exception等输出异常栈等常用的工具函数。\n应用实例\n\ntry:  \n    1/0  \nexcept Exception,e:  \n    print e\n    \n输出结果是\ninteger division or modulo by zero\n只知道是报了这个错，但是却不知道在哪个文件哪个函数哪一行报的错。\n使用 traceback 模块\nimport traceback  \ntry:  \n    1/0  \nexcept Exception,e:  \n    traceback.print_exc()  \n    \n输出结果是\nTraceback (most recent call last):\nFile \"test_traceback.py\", line 3, in <module>\n1/0\nZeroDivisionError: integer division or modulo by zero\n这样非常直观有利于调试。其实traceback.print_exc()函数只是traceback.print_exception()函数的一个简写形式，而它们获取异常相关的数据都是通过sys.exc_info()函数得到的。\ntraceback.print_exc()和traceback.format_exc()区别\nformat_exc()返回字符串，print_exc()直接给打印出来。即traceback.print_exc()与print traceback.format_exc()效果是一样的。print_exc()还可以接受file参数直接写入到一个文件。比如traceback.print_exc(file=open('tb.txt','w+'))写入到tb.txt文件中。\n\n我的博客即将搬运同步至腾讯云+社区，邀请大家一同入驻：https://cloud.tencent.com/dev...\n\n                ", "mainLikeNum": ["1 "], "mainBookmarkNum": "1"}